#!/bin/bash

BASE_DIR=$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)")

if [ "$1" == "" ]; then
  echo "ERROR: Usage docs [BUILD|CLEAN]";
  exit
fi

action=$(echo "${1}" | tr a-z A-Z)

case $action in
BUILD)
  cd "$BASE_DIR/asciidoc" || exit
  mvn process-resources
  rm -rf .asciidoctor
  ;;
CLEAN)
  cd "$BASE_DIR/docs" || exit
  rm *.html
  rm *.pdf
  rm -rf .asciidoctor
  rm -rf images
  rm -rf styles
  ;;
*)
  echo "action is invalid please choose BUILD or CLEAN"
  ;;
esac
